name: reverse-proxy

services:
    reverse-proxy-server:
        build:
            dockerfile_inline: |
                FROM nginx:mainline-alpine
                COPY nginx.conf /etc/nginx/nginx.conf

        ports:
            - "80:80"

        networks:
            - reverse-proxy-network

        develop:
            watch:
                - path: nginx.conf
                  target: /etc/nginx/nginx.conf
                  action: sync+restart

networks:
    reverse-proxy-network:
        driver: bridge
